# Generated by Django 5.2.9 on 2025-12-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Ex: number@upi or name@okicici', max_length=50, null=True),
        ),
    ]
