# Generated by Django 5.2.9 on 2025-12-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payer_name',
            field=models.CharField(blank=True, help_text='Paid by', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='UPI Ref ID / Txn ID', max_length=100, null=True),
        ),
    ]
