# Generated by Django 5.2.9 on 2025-12-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_order_payer_name_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Upload Screenshot if needed', null=True, upload_to='payment_proofs/'),
        ),
    ]
