# Generated by Django 5.2.9 on 2025-12-07 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_allowed_radius_restaurant_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('REGISTER', 'First Time'), ('RESET', 'Face Reset')], max_length=20)),
                ('old_face_image', models.ImageField(blank=True, null=True, upload_to='face_logs/old/')),
                ('new_face_image', models.ImageField(upload_to='face_logs/new/')),
                ('reset_count', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
