# Generated by Django 5.2.9 on 2025-12-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_facelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceLog',
        ),
    ]
