# Generated by Django 5.2.9 on 2025-12-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_remove_ownernotification_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Ex: 9876543210@paytm or merchant@upi', max_length=50, null=True),
        ),
    ]
